defaultBaseImage: gcr.io/distroless/static-debian13

defaultPlatforms:
  - linux/amd64
  - linux/arm64

builds:
  - id: github.com/actordock/actordock/cmd/envd
    main: ./cmd/envd
    baseImage: alpine
  - id: github.com/actordock/actordock/cmd/envd-python
    main: ./cmd/envd
    baseImage: docker.io/library/python:3.12-alpine
