// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// TODO: Here and everywhere, s/Session/Actor to align with the glossary.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: runtimeapi.proto

package runtimeapipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnapshotType int32

const (
	SnapshotType_SNAPSHOT_TYPE_UNSPECIFIED SnapshotType = 0
	SnapshotType_SNAPSHOT_TYPE_LOCAL       SnapshotType = 1
	SnapshotType_SNAPSHOT_TYPE_EXTERNAL    SnapshotType = 2
)

// Enum value maps for SnapshotType.
var (
	SnapshotType_name = map[int32]string{
		0: "SNAPSHOT_TYPE_UNSPECIFIED",
		1: "SNAPSHOT_TYPE_LOCAL",
		2: "SNAPSHOT_TYPE_EXTERNAL",
	}
	SnapshotType_value = map[string]int32{
		"SNAPSHOT_TYPE_UNSPECIFIED": 0,
		"SNAPSHOT_TYPE_LOCAL":       1,
		"SNAPSHOT_TYPE_EXTERNAL":    2,
	}
)

func (x SnapshotType) Enum() *SnapshotType {
	p := new(SnapshotType)
	*p = x
	return p
}

func (x SnapshotType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotType) Descriptor() protoreflect.EnumDescriptor {
	return file_runtimeapi_proto_enumTypes[0].Descriptor()
}

func (SnapshotType) Type() protoreflect.EnumType {
	return &file_runtimeapi_proto_enumTypes[0]
}

func (x SnapshotType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapshotType.Descriptor instead.
func (SnapshotType) EnumDescriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{0}
}

type Actor_Status int32

const (
	Actor_STATUS_UNSPECIFIED Actor_Status = 0
	Actor_STATUS_RESUMING    Actor_Status = 1
	Actor_STATUS_RUNNING     Actor_Status = 2
	Actor_STATUS_SUSPENDING  Actor_Status = 3
	Actor_STATUS_SUSPENDED   Actor_Status = 4
	Actor_STATUS_PAUSING     Actor_Status = 5
	Actor_STATUS_PAUSED      Actor_Status = 6
)

// Enum value maps for Actor_Status.
var (
	Actor_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_RESUMING",
		2: "STATUS_RUNNING",
		3: "STATUS_SUSPENDING",
		4: "STATUS_SUSPENDED",
		5: "STATUS_PAUSING",
		6: "STATUS_PAUSED",
	}
	Actor_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_RESUMING":    1,
		"STATUS_RUNNING":     2,
		"STATUS_SUSPENDING":  3,
		"STATUS_SUSPENDED":   4,
		"STATUS_PAUSING":     5,
		"STATUS_PAUSED":      6,
	}
)

func (x Actor_Status) Enum() *Actor_Status {
	p := new(Actor_Status)
	*p = x
	return p
}

func (x Actor_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Actor_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_runtimeapi_proto_enumTypes[1].Descriptor()
}

func (Actor_Status) Type() protoreflect.EnumType {
	return &file_runtimeapi_proto_enumTypes[1]
}

func (x Actor_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Actor_Status.Descriptor instead.
func (Actor_Status) EnumDescriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{4, 0}
}

type ExternalSnapshotInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SnapshotUriPrefix string                 `protobuf:"bytes,1,opt,name=snapshot_uri_prefix,json=snapshotUriPrefix,proto3" json:"snapshot_uri_prefix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExternalSnapshotInfo) Reset() {
	*x = ExternalSnapshotInfo{}
	mi := &file_runtimeapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalSnapshotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalSnapshotInfo) ProtoMessage() {}

func (x *ExternalSnapshotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalSnapshotInfo.ProtoReflect.Descriptor instead.
func (*ExternalSnapshotInfo) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{0}
}

func (x *ExternalSnapshotInfo) GetSnapshotUriPrefix() string {
	if x != nil {
		return x.SnapshotUriPrefix
	}
	return ""
}

type LocalSnapshotInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SnapshotPrefix string                 `protobuf:"bytes,1,opt,name=snapshot_prefix,json=snapshotPrefix,proto3" json:"snapshot_prefix,omitempty"`
	// Node VMs that have local snapshots for this actor, while it's PAUSED.
	NodeVmsWithLocalSnapshots []string `protobuf:"bytes,2,rep,name=node_vms_with_local_snapshots,json=nodeVmsWithLocalSnapshots,proto3" json:"node_vms_with_local_snapshots,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *LocalSnapshotInfo) Reset() {
	*x = LocalSnapshotInfo{}
	mi := &file_runtimeapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalSnapshotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSnapshotInfo) ProtoMessage() {}

func (x *LocalSnapshotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSnapshotInfo.ProtoReflect.Descriptor instead.
func (*LocalSnapshotInfo) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{1}
}

func (x *LocalSnapshotInfo) GetSnapshotPrefix() string {
	if x != nil {
		return x.SnapshotPrefix
	}
	return ""
}

func (x *LocalSnapshotInfo) GetNodeVmsWithLocalSnapshots() []string {
	if x != nil {
		return x.NodeVmsWithLocalSnapshots
	}
	return nil
}

type SnapshotInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  SnapshotType           `protobuf:"varint,1,opt,name=type,proto3,enum=actordock.runtimeapi.SnapshotType" json:"type,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*SnapshotInfo_External
	//	*SnapshotInfo_Local
	Data          isSnapshotInfo_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotInfo) Reset() {
	*x = SnapshotInfo{}
	mi := &file_runtimeapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotInfo) ProtoMessage() {}

func (x *SnapshotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotInfo.ProtoReflect.Descriptor instead.
func (*SnapshotInfo) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotInfo) GetType() SnapshotType {
	if x != nil {
		return x.Type
	}
	return SnapshotType_SNAPSHOT_TYPE_UNSPECIFIED
}

func (x *SnapshotInfo) GetData() isSnapshotInfo_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SnapshotInfo) GetExternal() *ExternalSnapshotInfo {
	if x != nil {
		if x, ok := x.Data.(*SnapshotInfo_External); ok {
			return x.External
		}
	}
	return nil
}

func (x *SnapshotInfo) GetLocal() *LocalSnapshotInfo {
	if x != nil {
		if x, ok := x.Data.(*SnapshotInfo_Local); ok {
			return x.Local
		}
	}
	return nil
}

type isSnapshotInfo_Data interface {
	isSnapshotInfo_Data()
}

type SnapshotInfo_External struct {
	External *ExternalSnapshotInfo `protobuf:"bytes,2,opt,name=external,proto3,oneof"`
}

type SnapshotInfo_Local struct {
	Local *LocalSnapshotInfo `protobuf:"bytes,3,opt,name=local,proto3,oneof"`
}

func (*SnapshotInfo_External) isSnapshotInfo_Data() {}

func (*SnapshotInfo_Local) isSnapshotInfo_Data() {}

// Selector matches worker pools by label.
// Only equality-based matching is supported.
type Selector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchLabels   map[string]string      `protobuf:"bytes,1,rep,name=match_labels,json=matchLabels,proto3" json:"match_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selector) Reset() {
	*x = Selector{}
	mi := &file_runtimeapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selector) ProtoMessage() {}

func (x *Selector) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selector.ProtoReflect.Descriptor instead.
func (*Selector) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{3}
}

func (x *Selector) GetMatchLabels() map[string]string {
	if x != nil {
		return x.MatchLabels
	}
	return nil
}

type Actor struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ActorId                string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Version                int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	ActorTemplateNamespace string                 `protobuf:"bytes,3,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	ActorTemplateName      string                 `protobuf:"bytes,4,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	Status                 Actor_Status           `protobuf:"varint,5,opt,name=status,proto3,enum=actordock.runtimeapi.Actor_Status" json:"status,omitempty"`
	SandboxPodNamespace    string                 `protobuf:"bytes,6,opt,name=sandbox_pod_namespace,json=sandboxPodNamespace,proto3" json:"sandbox_pod_namespace,omitempty"`
	SandboxPodName         string                 `protobuf:"bytes,7,opt,name=sandbox_pod_name,json=sandboxPodName,proto3" json:"sandbox_pod_name,omitempty"`
	SandboxPodIp           string                 `protobuf:"bytes,8,opt,name=sandbox_pod_ip,json=sandboxPodIp,proto3" json:"sandbox_pod_ip,omitempty"`
	InProgressSnapshot     string                 `protobuf:"bytes,10,opt,name=in_progress_snapshot,json=inProgressSnapshot,proto3" json:"in_progress_snapshot,omitempty"`
	SandboxPodUid          string                 `protobuf:"bytes,11,opt,name=sandbox_pod_uid,json=sandboxPodUid,proto3" json:"sandbox_pod_uid,omitempty"`
	LatestSnapshotInfo     *SnapshotInfo          `protobuf:"bytes,12,opt,name=latest_snapshot_info,json=latestSnapshotInfo,proto3" json:"latest_snapshot_info,omitempty"`
	// worker_selector is the per-actor placement constraint. The scheduler
	// evaluates the AND of this selector and the template's workerSelector to
	// find eligible pools. Set at CreateActor; may be updated at any time via
	// UpdateActor. Changes take effect on the next ResumeActor call.
	WorkerSelector *Selector `protobuf:"bytes,13,opt,name=worker_selector,json=workerSelector,proto3" json:"worker_selector,omitempty"`
	// worker_pool_name is the name of the WorkerPool that owns the currently
	// assigned worker, in the same namespace as sandbox_pod_namespace (pool and
	// pod namespaces always match). Set by the scheduler at assignment time
	// and cleared when the worker is freed. Needed to release the worker on
	// suspend/pause since eligibility is no longer a single fixed pool
	// reference on the ActorTemplate.
	WorkerPoolName string `protobuf:"bytes,14,opt,name=worker_pool_name,json=workerPoolName,proto3" json:"worker_pool_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_runtimeapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{4}
}

func (x *Actor) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Actor) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Actor) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *Actor) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *Actor) GetStatus() Actor_Status {
	if x != nil {
		return x.Status
	}
	return Actor_STATUS_UNSPECIFIED
}

func (x *Actor) GetSandboxPodNamespace() string {
	if x != nil {
		return x.SandboxPodNamespace
	}
	return ""
}

func (x *Actor) GetSandboxPodName() string {
	if x != nil {
		return x.SandboxPodName
	}
	return ""
}

func (x *Actor) GetSandboxPodIp() string {
	if x != nil {
		return x.SandboxPodIp
	}
	return ""
}

func (x *Actor) GetInProgressSnapshot() string {
	if x != nil {
		return x.InProgressSnapshot
	}
	return ""
}

func (x *Actor) GetSandboxPodUid() string {
	if x != nil {
		return x.SandboxPodUid
	}
	return ""
}

func (x *Actor) GetLatestSnapshotInfo() *SnapshotInfo {
	if x != nil {
		return x.LatestSnapshotInfo
	}
	return nil
}

func (x *Actor) GetWorkerSelector() *Selector {
	if x != nil {
		return x.WorkerSelector
	}
	return nil
}

func (x *Actor) GetWorkerPoolName() string {
	if x != nil {
		return x.WorkerPoolName
	}
	return ""
}

type GetActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActorRequest) Reset() {
	*x = GetActorRequest{}
	mi := &file_runtimeapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActorRequest) ProtoMessage() {}

func (x *GetActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActorRequest.ProtoReflect.Descriptor instead.
func (*GetActorRequest) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{5}
}

func (x *GetActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type GetActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActorResponse) Reset() {
	*x = GetActorResponse{}
	mi := &file_runtimeapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActorResponse) ProtoMessage() {}

func (x *GetActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActorResponse.ProtoReflect.Descriptor instead.
func (*GetActorResponse) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{6}
}

func (x *GetActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

// Request to create a new Actor.
type CreateActorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The custom identifier for the new Actor. Must be a valid DNS-1123 label.
	ActorId string `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// The namespace of the ActorTemplate to derive from.
	ActorTemplateNamespace string `protobuf:"bytes,2,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	// The name of the ActorTemplate to derive from.
	ActorTemplateName string `protobuf:"bytes,3,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	// worker_selector sets the actor's placement constraint at creation time.
	// If empty, the actor matches any pool admitted by the template's selector.
	WorkerSelector *Selector `protobuf:"bytes,4,opt,name=worker_selector,json=workerSelector,proto3" json:"worker_selector,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateActorRequest) Reset() {
	*x = CreateActorRequest{}
	mi := &file_runtimeapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActorRequest) ProtoMessage() {}

func (x *CreateActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActorRequest.ProtoReflect.Descriptor instead.
func (*CreateActorRequest) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{7}
}

func (x *CreateActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *CreateActorRequest) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *CreateActorRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *CreateActorRequest) GetWorkerSelector() *Selector {
	if x != nil {
		return x.WorkerSelector
	}
	return nil
}

type CreateActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActorResponse) Reset() {
	*x = CreateActorResponse{}
	mi := &file_runtimeapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActorResponse) ProtoMessage() {}

func (x *CreateActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActorResponse.ProtoReflect.Descriptor instead.
func (*CreateActorResponse) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{8}
}

func (x *CreateActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

// Request to update mutable fields on an existing Actor.
// May be called regardless of the actor's current status.
// Changes take effect on the next ResumeActor call.
type UpdateActorRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ActorId string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// worker_selector replaces the actor's current placement constraint.
	// Takes effect on the next ResumeActor call.
	WorkerSelector *Selector `protobuf:"bytes,2,opt,name=worker_selector,json=workerSelector,proto3" json:"worker_selector,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateActorRequest) Reset() {
	*x = UpdateActorRequest{}
	mi := &file_runtimeapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActorRequest) ProtoMessage() {}

func (x *UpdateActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActorRequest.ProtoReflect.Descriptor instead.
func (*UpdateActorRequest) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *UpdateActorRequest) GetWorkerSelector() *Selector {
	if x != nil {
		return x.WorkerSelector
	}
	return nil
}

type UpdateActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActorResponse) Reset() {
	*x = UpdateActorResponse{}
	mi := &file_runtimeapi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActorResponse) ProtoMessage() {}

func (x *UpdateActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActorResponse.ProtoReflect.Descriptor instead.
func (*UpdateActorResponse) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type SuspendActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendActorRequest) Reset() {
	*x = SuspendActorRequest{}
	mi := &file_runtimeapi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendActorRequest) ProtoMessage() {}

func (x *SuspendActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendActorRequest.ProtoReflect.Descriptor instead.
func (*SuspendActorRequest) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{11}
}

func (x *SuspendActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type SuspendActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendActorResponse) Reset() {
	*x = SuspendActorResponse{}
	mi := &file_runtimeapi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendActorResponse) ProtoMessage() {}

func (x *SuspendActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendActorResponse.ProtoReflect.Descriptor instead.
func (*SuspendActorResponse) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{12}
}

func (x *SuspendActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type PauseActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseActorRequest) Reset() {
	*x = PauseActorRequest{}
	mi := &file_runtimeapi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseActorRequest) ProtoMessage() {}

func (x *PauseActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseActorRequest.ProtoReflect.Descriptor instead.
func (*PauseActorRequest) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{13}
}

func (x *PauseActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type PauseActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseActorResponse) Reset() {
	*x = PauseActorResponse{}
	mi := &file_runtimeapi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseActorResponse) ProtoMessage() {}

func (x *PauseActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseActorResponse.ProtoReflect.Descriptor instead.
func (*PauseActorResponse) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{14}
}

func (x *PauseActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type ResumeActorRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ActorId string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// If true, skip golden snapshot and boot the workload from scratch.
	Boot          bool `protobuf:"varint,2,opt,name=boot,proto3" json:"boot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeActorRequest) Reset() {
	*x = ResumeActorRequest{}
	mi := &file_runtimeapi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeActorRequest) ProtoMessage() {}

func (x *ResumeActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeActorRequest.ProtoReflect.Descriptor instead.
func (*ResumeActorRequest) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{15}
}

func (x *ResumeActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ResumeActorRequest) GetBoot() bool {
	if x != nil {
		return x.Boot
	}
	return false
}

type ResumeActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeActorResponse) Reset() {
	*x = ResumeActorResponse{}
	mi := &file_runtimeapi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeActorResponse) ProtoMessage() {}

func (x *ResumeActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeActorResponse.ProtoReflect.Descriptor instead.
func (*ResumeActorResponse) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{16}
}

func (x *ResumeActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type DeleteActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteActorRequest) Reset() {
	*x = DeleteActorRequest{}
	mi := &file_runtimeapi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActorRequest) ProtoMessage() {}

func (x *DeleteActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActorRequest.ProtoReflect.Descriptor instead.
func (*DeleteActorRequest) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type DeleteActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteActorResponse) Reset() {
	*x = DeleteActorResponse{}
	mi := &file_runtimeapi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActorResponse) ProtoMessage() {}

func (x *DeleteActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActorResponse.ProtoReflect.Descriptor instead.
func (*DeleteActorResponse) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{18}
}

type ListWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersRequest) Reset() {
	*x = ListWorkersRequest{}
	mi := &file_runtimeapi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersRequest) ProtoMessage() {}

func (x *ListWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersRequest.ProtoReflect.Descriptor instead.
func (*ListWorkersRequest) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{19}
}

type ListWorkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*Worker              `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersResponse) Reset() {
	*x = ListWorkersResponse{}
	mi := &file_runtimeapi_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersResponse) ProtoMessage() {}

func (x *ListWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkersResponse) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{20}
}

func (x *ListWorkersResponse) GetWorkers() []*Worker {
	if x != nil {
		return x.Workers
	}
	return nil
}

// Request to list actors with pagination.
// This operation provides "soft" guarantees: actors may be missed or duplicated
// if the system state changes during pagination.
type ListActorsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of actors to return. The server may enforce a hard limit
	// (e.g., 1000) regardless of the requested size.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// An opaque pagination token obtained from a previous ListActorsResponse.
	// Empty for the first request.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActorsRequest) Reset() {
	*x = ListActorsRequest{}
	mi := &file_runtimeapi_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActorsRequest) ProtoMessage() {}

func (x *ListActorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActorsRequest.ProtoReflect.Descriptor instead.
func (*ListActorsRequest) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{21}
}

func (x *ListActorsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListActorsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response for a ListActors operation.
type ListActorsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The page of actors. This list may be empty even if there are more results.
	Actors []*Actor `protobuf:"bytes,1,rep,name=actors,proto3" json:"actors,omitempty"`
	// An opaque token to retrieve the next page of results.
	// If empty, there are no more results. Clients must loop until this is empty.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActorsResponse) Reset() {
	*x = ListActorsResponse{}
	mi := &file_runtimeapi_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActorsResponse) ProtoMessage() {}

func (x *ListActorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActorsResponse.ProtoReflect.Descriptor instead.
func (*ListActorsResponse) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{22}
}

func (x *ListActorsResponse) GetActors() []*Actor {
	if x != nil {
		return x.Actors
	}
	return nil
}

func (x *ListActorsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type Worker struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerNamespace string                 `protobuf:"bytes,1,opt,name=worker_namespace,json=workerNamespace,proto3" json:"worker_namespace,omitempty"`
	WorkerPool      string                 `protobuf:"bytes,2,opt,name=worker_pool,json=workerPool,proto3" json:"worker_pool,omitempty"`
	WorkerPod       string                 `protobuf:"bytes,3,opt,name=worker_pod,json=workerPod,proto3" json:"worker_pod,omitempty"`
	ActorNamespace  string                 `protobuf:"bytes,4,opt,name=actor_namespace,json=actorNamespace,proto3" json:"actor_namespace,omitempty"`
	ActorTemplate   string                 `protobuf:"bytes,5,opt,name=actor_template,json=actorTemplate,proto3" json:"actor_template,omitempty"`
	ActorId         string                 `protobuf:"bytes,6,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Ip              string                 `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	Version         int64                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	WorkerPodUid    string                 `protobuf:"bytes,9,opt,name=worker_pod_uid,json=workerPodUid,proto3" json:"worker_pod_uid,omitempty"`
	NodeName        string                 `protobuf:"bytes,10,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_runtimeapi_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{23}
}

func (x *Worker) GetWorkerNamespace() string {
	if x != nil {
		return x.WorkerNamespace
	}
	return ""
}

func (x *Worker) GetWorkerPool() string {
	if x != nil {
		return x.WorkerPool
	}
	return ""
}

func (x *Worker) GetWorkerPod() string {
	if x != nil {
		return x.WorkerPod
	}
	return ""
}

func (x *Worker) GetActorNamespace() string {
	if x != nil {
		return x.ActorNamespace
	}
	return ""
}

func (x *Worker) GetActorTemplate() string {
	if x != nil {
		return x.ActorTemplate
	}
	return ""
}

func (x *Worker) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Worker) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Worker) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Worker) GetWorkerPodUid() string {
	if x != nil {
		return x.WorkerPodUid
	}
	return ""
}

func (x *Worker) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type DebugClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugClearRequest) Reset() {
	*x = DebugClearRequest{}
	mi := &file_runtimeapi_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugClearRequest) ProtoMessage() {}

func (x *DebugClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugClearRequest.ProtoReflect.Descriptor instead.
func (*DebugClearRequest) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{24}
}

type DebugClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugClearResponse) Reset() {
	*x = DebugClearResponse{}
	mi := &file_runtimeapi_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugClearResponse) ProtoMessage() {}

func (x *DebugClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugClearResponse.ProtoReflect.Descriptor instead.
func (*DebugClearResponse) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{25}
}

type MintJWTRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audience      []string               `protobuf:"bytes,1,rep,name=audience,proto3" json:"audience,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintJWTRequest) Reset() {
	*x = MintJWTRequest{}
	mi := &file_runtimeapi_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintJWTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintJWTRequest) ProtoMessage() {}

func (x *MintJWTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintJWTRequest.ProtoReflect.Descriptor instead.
func (*MintJWTRequest) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{26}
}

func (x *MintJWTRequest) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *MintJWTRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *MintJWTRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MintJWTRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type MintJWTResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session JWT.  An OIDC Discovery-compatible JWT
	//
	// Claims:
	//
	//   - iss: Issuer - a valid URL where a relying party can fetch the OIDC
	//     discovery documents.
	//   - sub: Subject - a string expressing the identity carried in the
	//
	// credential. Format
	//
	//	`app/${appid}/user/${userid}/session/${sessionid}`.
	//   - aud: Audience - a string identifying the service this token will be used
	//     to authenticate to.
	//   - nbf: Not Before - a numeric unix timestamp
	//   - exp: Expiration - a numeric unix timestamp
	//   - iat: Issued At - a numeric unix timestamp
	//   - `actordock.dev`: Actordock extension - JSON object
	//   - appID: (string) The Actordock App ID
	//   - userID: (string) The Actordock User ID
	//   - sessionID: (string) The Actordock Session ID
	SessionJwt    string `protobuf:"bytes,1,opt,name=session_jwt,json=sessionJwt,proto3" json:"session_jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintJWTResponse) Reset() {
	*x = MintJWTResponse{}
	mi := &file_runtimeapi_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintJWTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintJWTResponse) ProtoMessage() {}

func (x *MintJWTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintJWTResponse.ProtoReflect.Descriptor instead.
func (*MintJWTResponse) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{27}
}

func (x *MintJWTResponse) GetSessionJwt() string {
	if x != nil {
		return x.SessionJwt
	}
	return ""
}

type MintCertRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AppId     string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Request contains DER encoded bytes of a x509 certificate signing request.
	// The signer will ignore the contents of the CSR except to extract the
	// subject public key.
	CertificateSigningRequest []byte `protobuf:"bytes,4,opt,name=certificate_signing_request,json=certificateSigningRequest,proto3" json:"certificate_signing_request,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MintCertRequest) Reset() {
	*x = MintCertRequest{}
	mi := &file_runtimeapi_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintCertRequest) ProtoMessage() {}

func (x *MintCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintCertRequest.ProtoReflect.Descriptor instead.
func (*MintCertRequest) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{28}
}

func (x *MintCertRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *MintCertRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MintCertRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MintCertRequest) GetCertificateSigningRequest() []byte {
	if x != nil {
		return x.CertificateSigningRequest
	}
	return nil
}

type MintCertResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response contains a list of DER encoded certificates. The first entry is the
	// leaf certificate, and any remaining entries are intermediates in
	// leaf-to-root order.
	SessionCertificates [][]byte `protobuf:"bytes,1,rep,name=session_certificates,json=sessionCertificates,proto3" json:"session_certificates,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MintCertResponse) Reset() {
	*x = MintCertResponse{}
	mi := &file_runtimeapi_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintCertResponse) ProtoMessage() {}

func (x *MintCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeapi_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintCertResponse.ProtoReflect.Descriptor instead.
func (*MintCertResponse) Descriptor() ([]byte, []int) {
	return file_runtimeapi_proto_rawDescGZIP(), []int{29}
}

func (x *MintCertResponse) GetSessionCertificates() [][]byte {
	if x != nil {
		return x.SessionCertificates
	}
	return nil
}

var File_runtimeapi_proto protoreflect.FileDescriptor

const file_runtimeapi_proto_rawDesc = "" +
	"\n" +
	"\x10runtimeapi.proto\x12\x14actordock.runtimeapi\"F\n" +
	"\x14ExternalSnapshotInfo\x12.\n" +
	"\x13snapshot_uri_prefix\x18\x01 \x01(\tR\x11snapshotUriPrefix\"~\n" +
	"\x11LocalSnapshotInfo\x12'\n" +
	"\x0fsnapshot_prefix\x18\x01 \x01(\tR\x0esnapshotPrefix\x12@\n" +
	"\x1dnode_vms_with_local_snapshots\x18\x02 \x03(\tR\x19nodeVmsWithLocalSnapshots\"\xd9\x01\n" +
	"\fSnapshotInfo\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".actordock.runtimeapi.SnapshotTypeR\x04type\x12H\n" +
	"\bexternal\x18\x02 \x01(\v2*.actordock.runtimeapi.ExternalSnapshotInfoH\x00R\bexternal\x12?\n" +
	"\x05local\x18\x03 \x01(\v2'.actordock.runtimeapi.LocalSnapshotInfoH\x00R\x05localB\x06\n" +
	"\x04data\"\x9e\x01\n" +
	"\bSelector\x12R\n" +
	"\fmatch_labels\x18\x01 \x03(\v2/.actordock.runtimeapi.Selector.MatchLabelsEntryR\vmatchLabels\x1a>\n" +
	"\x10MatchLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x06\n" +
	"\x05Actor\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x128\n" +
	"\x18actor_template_namespace\x18\x03 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x04 \x01(\tR\x11actorTemplateName\x12:\n" +
	"\x06status\x18\x05 \x01(\x0e2\".actordock.runtimeapi.Actor.StatusR\x06status\x122\n" +
	"\x15sandbox_pod_namespace\x18\x06 \x01(\tR\x13sandboxPodNamespace\x12(\n" +
	"\x10sandbox_pod_name\x18\a \x01(\tR\x0esandboxPodName\x12$\n" +
	"\x0esandbox_pod_ip\x18\b \x01(\tR\fsandboxPodIp\x120\n" +
	"\x14in_progress_snapshot\x18\n" +
	" \x01(\tR\x12inProgressSnapshot\x12&\n" +
	"\x0fsandbox_pod_uid\x18\v \x01(\tR\rsandboxPodUid\x12T\n" +
	"\x14latest_snapshot_info\x18\f \x01(\v2\".actordock.runtimeapi.SnapshotInfoR\x12latestSnapshotInfo\x12G\n" +
	"\x0fworker_selector\x18\r \x01(\v2\x1e.actordock.runtimeapi.SelectorR\x0eworkerSelector\x12(\n" +
	"\x10worker_pool_name\x18\x0e \x01(\tR\x0eworkerPoolName\"\x9d\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTATUS_RESUMING\x10\x01\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x02\x12\x15\n" +
	"\x11STATUS_SUSPENDING\x10\x03\x12\x14\n" +
	"\x10STATUS_SUSPENDED\x10\x04\x12\x12\n" +
	"\x0eSTATUS_PAUSING\x10\x05\x12\x11\n" +
	"\rSTATUS_PAUSED\x10\x06J\x04\b\t\x10\n" +
	"\",\n" +
	"\x0fGetActorRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\"E\n" +
	"\x10GetActorResponse\x121\n" +
	"\x05actor\x18\x01 \x01(\v2\x1b.actordock.runtimeapi.ActorR\x05actor\"\xe2\x01\n" +
	"\x12CreateActorRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x128\n" +
	"\x18actor_template_namespace\x18\x02 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x03 \x01(\tR\x11actorTemplateName\x12G\n" +
	"\x0fworker_selector\x18\x04 \x01(\v2\x1e.actordock.runtimeapi.SelectorR\x0eworkerSelector\"H\n" +
	"\x13CreateActorResponse\x121\n" +
	"\x05actor\x18\x01 \x01(\v2\x1b.actordock.runtimeapi.ActorR\x05actor\"x\n" +
	"\x12UpdateActorRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12G\n" +
	"\x0fworker_selector\x18\x02 \x01(\v2\x1e.actordock.runtimeapi.SelectorR\x0eworkerSelector\"H\n" +
	"\x13UpdateActorResponse\x121\n" +
	"\x05actor\x18\x01 \x01(\v2\x1b.actordock.runtimeapi.ActorR\x05actor\"0\n" +
	"\x13SuspendActorRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\"I\n" +
	"\x14SuspendActorResponse\x121\n" +
	"\x05actor\x18\x01 \x01(\v2\x1b.actordock.runtimeapi.ActorR\x05actor\".\n" +
	"\x11PauseActorRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\"G\n" +
	"\x12PauseActorResponse\x121\n" +
	"\x05actor\x18\x01 \x01(\v2\x1b.actordock.runtimeapi.ActorR\x05actor\"C\n" +
	"\x12ResumeActorRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x12\n" +
	"\x04boot\x18\x02 \x01(\bR\x04boot\"H\n" +
	"\x13ResumeActorResponse\x121\n" +
	"\x05actor\x18\x01 \x01(\v2\x1b.actordock.runtimeapi.ActorR\x05actor\"/\n" +
	"\x12DeleteActorRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\"\x15\n" +
	"\x13DeleteActorResponse\"\x14\n" +
	"\x12ListWorkersRequest\"M\n" +
	"\x13ListWorkersResponse\x126\n" +
	"\aworkers\x18\x01 \x03(\v2\x1c.actordock.runtimeapi.WorkerR\aworkers\"O\n" +
	"\x11ListActorsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"q\n" +
	"\x12ListActorsResponse\x123\n" +
	"\x06actors\x18\x01 \x03(\v2\x1b.actordock.runtimeapi.ActorR\x06actors\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xcb\x02\n" +
	"\x06Worker\x12)\n" +
	"\x10worker_namespace\x18\x01 \x01(\tR\x0fworkerNamespace\x12\x1f\n" +
	"\vworker_pool\x18\x02 \x01(\tR\n" +
	"workerPool\x12\x1d\n" +
	"\n" +
	"worker_pod\x18\x03 \x01(\tR\tworkerPod\x12'\n" +
	"\x0factor_namespace\x18\x04 \x01(\tR\x0eactorNamespace\x12%\n" +
	"\x0eactor_template\x18\x05 \x01(\tR\ractorTemplate\x12\x19\n" +
	"\bactor_id\x18\x06 \x01(\tR\aactorId\x12\x0e\n" +
	"\x02ip\x18\a \x01(\tR\x02ip\x12\x18\n" +
	"\aversion\x18\b \x01(\x03R\aversion\x12$\n" +
	"\x0eworker_pod_uid\x18\t \x01(\tR\fworkerPodUid\x12\x1b\n" +
	"\tnode_name\x18\n" +
	" \x01(\tR\bnodeName\"\x13\n" +
	"\x11DebugClearRequest\"\x14\n" +
	"\x12DebugClearResponse\"{\n" +
	"\x0eMintJWTRequest\x12\x1a\n" +
	"\baudience\x18\x01 \x03(\tR\baudience\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"2\n" +
	"\x0fMintJWTResponse\x12\x1f\n" +
	"\vsession_jwt\x18\x01 \x01(\tR\n" +
	"sessionJwt\"\xa0\x01\n" +
	"\x0fMintCertRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12>\n" +
	"\x1bcertificate_signing_request\x18\x04 \x01(\fR\x19certificateSigningRequest\"E\n" +
	"\x10MintCertResponse\x121\n" +
	"\x14session_certificates\x18\x01 \x03(\fR\x13sessionCertificates*b\n" +
	"\fSnapshotType\x12\x1d\n" +
	"\x19SNAPSHOT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SNAPSHOT_TYPE_LOCAL\x10\x01\x12\x1a\n" +
	"\x16SNAPSHOT_TYPE_EXTERNAL\x10\x022\xf6\a\n" +
	"\aControl\x12[\n" +
	"\bGetActor\x12%.actordock.runtimeapi.GetActorRequest\x1a&.actordock.runtimeapi.GetActorResponse\"\x00\x12d\n" +
	"\vCreateActor\x12(.actordock.runtimeapi.CreateActorRequest\x1a).actordock.runtimeapi.CreateActorResponse\"\x00\x12d\n" +
	"\vUpdateActor\x12(.actordock.runtimeapi.UpdateActorRequest\x1a).actordock.runtimeapi.UpdateActorResponse\"\x00\x12g\n" +
	"\fSuspendActor\x12).actordock.runtimeapi.SuspendActorRequest\x1a*.actordock.runtimeapi.SuspendActorResponse\"\x00\x12a\n" +
	"\n" +
	"PauseActor\x12'.actordock.runtimeapi.PauseActorRequest\x1a(.actordock.runtimeapi.PauseActorResponse\"\x00\x12d\n" +
	"\vResumeActor\x12(.actordock.runtimeapi.ResumeActorRequest\x1a).actordock.runtimeapi.ResumeActorResponse\"\x00\x12d\n" +
	"\vDeleteActor\x12(.actordock.runtimeapi.DeleteActorRequest\x1a).actordock.runtimeapi.DeleteActorResponse\"\x00\x12d\n" +
	"\vListWorkers\x12(.actordock.runtimeapi.ListWorkersRequest\x1a).actordock.runtimeapi.ListWorkersResponse\"\x00\x12a\n" +
	"\n" +
	"ListActors\x12'.actordock.runtimeapi.ListActorsRequest\x1a(.actordock.runtimeapi.ListActorsResponse\"\x00\x12a\n" +
	"\n" +
	"DebugClear\x12'.actordock.runtimeapi.DebugClearRequest\x1a(.actordock.runtimeapi.DebugClearResponse\"\x002\xc4\x01\n" +
	"\x0fSessionIdentity\x12V\n" +
	"\aMintJWT\x12$.actordock.runtimeapi.MintJWTRequest\x1a%.actordock.runtimeapi.MintJWTResponse\x12Y\n" +
	"\bMintCert\x12%.actordock.runtimeapi.MintCertRequest\x1a&.actordock.runtimeapi.MintCertResponseB5Z3github.com/actordock/runtime/pkg/proto/runtimeapipbb\x06proto3"

var (
	file_runtimeapi_proto_rawDescOnce sync.Once
	file_runtimeapi_proto_rawDescData []byte
)

func file_runtimeapi_proto_rawDescGZIP() []byte {
	file_runtimeapi_proto_rawDescOnce.Do(func() {
		file_runtimeapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtimeapi_proto_rawDesc), len(file_runtimeapi_proto_rawDesc)))
	})
	return file_runtimeapi_proto_rawDescData
}

var file_runtimeapi_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_runtimeapi_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_runtimeapi_proto_goTypes = []any{
	(SnapshotType)(0),            // 0: actordock.runtimeapi.SnapshotType
	(Actor_Status)(0),            // 1: actordock.runtimeapi.Actor.Status
	(*ExternalSnapshotInfo)(nil), // 2: actordock.runtimeapi.ExternalSnapshotInfo
	(*LocalSnapshotInfo)(nil),    // 3: actordock.runtimeapi.LocalSnapshotInfo
	(*SnapshotInfo)(nil),         // 4: actordock.runtimeapi.SnapshotInfo
	(*Selector)(nil),             // 5: actordock.runtimeapi.Selector
	(*Actor)(nil),                // 6: actordock.runtimeapi.Actor
	(*GetActorRequest)(nil),      // 7: actordock.runtimeapi.GetActorRequest
	(*GetActorResponse)(nil),     // 8: actordock.runtimeapi.GetActorResponse
	(*CreateActorRequest)(nil),   // 9: actordock.runtimeapi.CreateActorRequest
	(*CreateActorResponse)(nil),  // 10: actordock.runtimeapi.CreateActorResponse
	(*UpdateActorRequest)(nil),   // 11: actordock.runtimeapi.UpdateActorRequest
	(*UpdateActorResponse)(nil),  // 12: actordock.runtimeapi.UpdateActorResponse
	(*SuspendActorRequest)(nil),  // 13: actordock.runtimeapi.SuspendActorRequest
	(*SuspendActorResponse)(nil), // 14: actordock.runtimeapi.SuspendActorResponse
	(*PauseActorRequest)(nil),    // 15: actordock.runtimeapi.PauseActorRequest
	(*PauseActorResponse)(nil),   // 16: actordock.runtimeapi.PauseActorResponse
	(*ResumeActorRequest)(nil),   // 17: actordock.runtimeapi.ResumeActorRequest
	(*ResumeActorResponse)(nil),  // 18: actordock.runtimeapi.ResumeActorResponse
	(*DeleteActorRequest)(nil),   // 19: actordock.runtimeapi.DeleteActorRequest
	(*DeleteActorResponse)(nil),  // 20: actordock.runtimeapi.DeleteActorResponse
	(*ListWorkersRequest)(nil),   // 21: actordock.runtimeapi.ListWorkersRequest
	(*ListWorkersResponse)(nil),  // 22: actordock.runtimeapi.ListWorkersResponse
	(*ListActorsRequest)(nil),    // 23: actordock.runtimeapi.ListActorsRequest
	(*ListActorsResponse)(nil),   // 24: actordock.runtimeapi.ListActorsResponse
	(*Worker)(nil),               // 25: actordock.runtimeapi.Worker
	(*DebugClearRequest)(nil),    // 26: actordock.runtimeapi.DebugClearRequest
	(*DebugClearResponse)(nil),   // 27: actordock.runtimeapi.DebugClearResponse
	(*MintJWTRequest)(nil),       // 28: actordock.runtimeapi.MintJWTRequest
	(*MintJWTResponse)(nil),      // 29: actordock.runtimeapi.MintJWTResponse
	(*MintCertRequest)(nil),      // 30: actordock.runtimeapi.MintCertRequest
	(*MintCertResponse)(nil),     // 31: actordock.runtimeapi.MintCertResponse
	nil,                          // 32: actordock.runtimeapi.Selector.MatchLabelsEntry
}
var file_runtimeapi_proto_depIdxs = []int32{
	0,  // 0: actordock.runtimeapi.SnapshotInfo.type:type_name -> actordock.runtimeapi.SnapshotType
	2,  // 1: actordock.runtimeapi.SnapshotInfo.external:type_name -> actordock.runtimeapi.ExternalSnapshotInfo
	3,  // 2: actordock.runtimeapi.SnapshotInfo.local:type_name -> actordock.runtimeapi.LocalSnapshotInfo
	32, // 3: actordock.runtimeapi.Selector.match_labels:type_name -> actordock.runtimeapi.Selector.MatchLabelsEntry
	1,  // 4: actordock.runtimeapi.Actor.status:type_name -> actordock.runtimeapi.Actor.Status
	4,  // 5: actordock.runtimeapi.Actor.latest_snapshot_info:type_name -> actordock.runtimeapi.SnapshotInfo
	5,  // 6: actordock.runtimeapi.Actor.worker_selector:type_name -> actordock.runtimeapi.Selector
	6,  // 7: actordock.runtimeapi.GetActorResponse.actor:type_name -> actordock.runtimeapi.Actor
	5,  // 8: actordock.runtimeapi.CreateActorRequest.worker_selector:type_name -> actordock.runtimeapi.Selector
	6,  // 9: actordock.runtimeapi.CreateActorResponse.actor:type_name -> actordock.runtimeapi.Actor
	5,  // 10: actordock.runtimeapi.UpdateActorRequest.worker_selector:type_name -> actordock.runtimeapi.Selector
	6,  // 11: actordock.runtimeapi.UpdateActorResponse.actor:type_name -> actordock.runtimeapi.Actor
	6,  // 12: actordock.runtimeapi.SuspendActorResponse.actor:type_name -> actordock.runtimeapi.Actor
	6,  // 13: actordock.runtimeapi.PauseActorResponse.actor:type_name -> actordock.runtimeapi.Actor
	6,  // 14: actordock.runtimeapi.ResumeActorResponse.actor:type_name -> actordock.runtimeapi.Actor
	25, // 15: actordock.runtimeapi.ListWorkersResponse.workers:type_name -> actordock.runtimeapi.Worker
	6,  // 16: actordock.runtimeapi.ListActorsResponse.actors:type_name -> actordock.runtimeapi.Actor
	7,  // 17: actordock.runtimeapi.Control.GetActor:input_type -> actordock.runtimeapi.GetActorRequest
	9,  // 18: actordock.runtimeapi.Control.CreateActor:input_type -> actordock.runtimeapi.CreateActorRequest
	11, // 19: actordock.runtimeapi.Control.UpdateActor:input_type -> actordock.runtimeapi.UpdateActorRequest
	13, // 20: actordock.runtimeapi.Control.SuspendActor:input_type -> actordock.runtimeapi.SuspendActorRequest
	15, // 21: actordock.runtimeapi.Control.PauseActor:input_type -> actordock.runtimeapi.PauseActorRequest
	17, // 22: actordock.runtimeapi.Control.ResumeActor:input_type -> actordock.runtimeapi.ResumeActorRequest
	19, // 23: actordock.runtimeapi.Control.DeleteActor:input_type -> actordock.runtimeapi.DeleteActorRequest
	21, // 24: actordock.runtimeapi.Control.ListWorkers:input_type -> actordock.runtimeapi.ListWorkersRequest
	23, // 25: actordock.runtimeapi.Control.ListActors:input_type -> actordock.runtimeapi.ListActorsRequest
	26, // 26: actordock.runtimeapi.Control.DebugClear:input_type -> actordock.runtimeapi.DebugClearRequest
	28, // 27: actordock.runtimeapi.SessionIdentity.MintJWT:input_type -> actordock.runtimeapi.MintJWTRequest
	30, // 28: actordock.runtimeapi.SessionIdentity.MintCert:input_type -> actordock.runtimeapi.MintCertRequest
	8,  // 29: actordock.runtimeapi.Control.GetActor:output_type -> actordock.runtimeapi.GetActorResponse
	10, // 30: actordock.runtimeapi.Control.CreateActor:output_type -> actordock.runtimeapi.CreateActorResponse
	12, // 31: actordock.runtimeapi.Control.UpdateActor:output_type -> actordock.runtimeapi.UpdateActorResponse
	14, // 32: actordock.runtimeapi.Control.SuspendActor:output_type -> actordock.runtimeapi.SuspendActorResponse
	16, // 33: actordock.runtimeapi.Control.PauseActor:output_type -> actordock.runtimeapi.PauseActorResponse
	18, // 34: actordock.runtimeapi.Control.ResumeActor:output_type -> actordock.runtimeapi.ResumeActorResponse
	20, // 35: actordock.runtimeapi.Control.DeleteActor:output_type -> actordock.runtimeapi.DeleteActorResponse
	22, // 36: actordock.runtimeapi.Control.ListWorkers:output_type -> actordock.runtimeapi.ListWorkersResponse
	24, // 37: actordock.runtimeapi.Control.ListActors:output_type -> actordock.runtimeapi.ListActorsResponse
	27, // 38: actordock.runtimeapi.Control.DebugClear:output_type -> actordock.runtimeapi.DebugClearResponse
	29, // 39: actordock.runtimeapi.SessionIdentity.MintJWT:output_type -> actordock.runtimeapi.MintJWTResponse
	31, // 40: actordock.runtimeapi.SessionIdentity.MintCert:output_type -> actordock.runtimeapi.MintCertResponse
	29, // [29:41] is the sub-list for method output_type
	17, // [17:29] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_runtimeapi_proto_init() }
func file_runtimeapi_proto_init() {
	if File_runtimeapi_proto != nil {
		return
	}
	file_runtimeapi_proto_msgTypes[2].OneofWrappers = []any{
		(*SnapshotInfo_External)(nil),
		(*SnapshotInfo_Local)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtimeapi_proto_rawDesc), len(file_runtimeapi_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_runtimeapi_proto_goTypes,
		DependencyIndexes: file_runtimeapi_proto_depIdxs,
		EnumInfos:         file_runtimeapi_proto_enumTypes,
		MessageInfos:      file_runtimeapi_proto_msgTypes,
	}.Build()
	File_runtimeapi_proto = out.File
	file_runtimeapi_proto_goTypes = nil
	file_runtimeapi_proto_depIdxs = nil
}
