// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: runtimeworker.proto

package runtimeworkerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VolumeType int32

const (
	VolumeType_VOLUME_TYPE_UNSPECIFIED VolumeType = 0
	VolumeType_VOLUME_TYPE_DURABLE_DIR VolumeType = 1
)

// Enum value maps for VolumeType.
var (
	VolumeType_name = map[int32]string{
		0: "VOLUME_TYPE_UNSPECIFIED",
		1: "VOLUME_TYPE_DURABLE_DIR",
	}
	VolumeType_value = map[string]int32{
		"VOLUME_TYPE_UNSPECIFIED": 0,
		"VOLUME_TYPE_DURABLE_DIR": 1,
	}
)

func (x VolumeType) Enum() *VolumeType {
	p := new(VolumeType)
	*p = x
	return p
}

func (x VolumeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VolumeType) Descriptor() protoreflect.EnumDescriptor {
	return file_runtimeworker_proto_enumTypes[0].Descriptor()
}

func (VolumeType) Type() protoreflect.EnumType {
	return &file_runtimeworker_proto_enumTypes[0]
}

func (x VolumeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VolumeType.Descriptor instead.
func (VolumeType) EnumDescriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{0}
}

type CheckpointType int32

const (
	// Should never happen
	CheckpointType_CHECKPOINT_TYPE_UNSPECIFIED CheckpointType = 0
	// Save snapshot only in local filesystem
	CheckpointType_CHECKPOINT_TYPE_LOCAL CheckpointType = 1
	// Save snapshot to object storage
	CheckpointType_CHECKPOINT_TYPE_EXTERNAL CheckpointType = 2
)

// Enum value maps for CheckpointType.
var (
	CheckpointType_name = map[int32]string{
		0: "CHECKPOINT_TYPE_UNSPECIFIED",
		1: "CHECKPOINT_TYPE_LOCAL",
		2: "CHECKPOINT_TYPE_EXTERNAL",
	}
	CheckpointType_value = map[string]int32{
		"CHECKPOINT_TYPE_UNSPECIFIED": 0,
		"CHECKPOINT_TYPE_LOCAL":       1,
		"CHECKPOINT_TYPE_EXTERNAL":    2,
	}
)

func (x CheckpointType) Enum() *CheckpointType {
	p := new(CheckpointType)
	*p = x
	return p
}

func (x CheckpointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckpointType) Descriptor() protoreflect.EnumDescriptor {
	return file_runtimeworker_proto_enumTypes[1].Descriptor()
}

func (CheckpointType) Type() protoreflect.EnumType {
	return &file_runtimeworker_proto_enumTypes[1]
}

func (x CheckpointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckpointType.Descriptor instead.
func (CheckpointType) EnumDescriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{1}
}

type SnapshotScope int32

const (
	// Not valid option; should never happen.
	SnapshotScope_SNAPSHOT_SCOPE_UNSPECIFIED SnapshotScope = 0
	// Capture process memory plus the full filesystem delta on top of the OCI
	// image (including any attached DurableDir volumes).
	SnapshotScope_SNAPSHOT_SCOPE_FULL SnapshotScope = 1
	// Capture only the contents of attached volumes that support snapshots
	// (currently DurableDir-typed volumes). Memory and the rest of rootfs are
	// excluded.
	SnapshotScope_SNAPSHOT_SCOPE_DATA SnapshotScope = 2
)

// Enum value maps for SnapshotScope.
var (
	SnapshotScope_name = map[int32]string{
		0: "SNAPSHOT_SCOPE_UNSPECIFIED",
		1: "SNAPSHOT_SCOPE_FULL",
		2: "SNAPSHOT_SCOPE_DATA",
	}
	SnapshotScope_value = map[string]int32{
		"SNAPSHOT_SCOPE_UNSPECIFIED": 0,
		"SNAPSHOT_SCOPE_FULL":        1,
		"SNAPSHOT_SCOPE_DATA":        2,
	}
)

func (x SnapshotScope) Enum() *SnapshotScope {
	p := new(SnapshotScope)
	*p = x
	return p
}

func (x SnapshotScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotScope) Descriptor() protoreflect.EnumDescriptor {
	return file_runtimeworker_proto_enumTypes[2].Descriptor()
}

func (SnapshotScope) Type() protoreflect.EnumType {
	return &file_runtimeworker_proto_enumTypes[2]
}

func (x SnapshotScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapshotScope.Descriptor instead.
func (SnapshotScope) EnumDescriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{2}
}

type RunRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TargetSandboxPodUid    string                 `protobuf:"bytes,1,opt,name=target_sandbox_pod_uid,json=targetSandboxPodUid,proto3" json:"target_sandbox_pod_uid,omitempty"`
	ActorTemplateNamespace string                 `protobuf:"bytes,3,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	ActorTemplateName      string                 `protobuf:"bytes,4,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	ActorId                string                 `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Spec                   *WorkloadSpec          `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	// The sandbox binaries to use for booting this actor from scratch. runtime-worker
	// fetches the relevant assets and records them with the actor's on-node state
	// so a later Checkpoint can pin the same version into the snapshot manifest.
	SandboxAssets *SandboxAssets `protobuf:"bytes,9,opt,name=sandbox_assets,json=sandboxAssets,proto3" json:"sandbox_assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_runtimeworker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetTargetSandboxPodUid() string {
	if x != nil {
		return x.TargetSandboxPodUid
	}
	return ""
}

func (x *RunRequest) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *RunRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *RunRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *RunRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *RunRequest) GetSandboxAssets() *SandboxAssets {
	if x != nil {
		return x.SandboxAssets
	}
	return nil
}

// AssetFile is one content-addressed file runtime-worker fetches for a sandbox runtime
// (e.g. the gVisor runsc binary).
type AssetFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gs:// URL to download the asset from.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Lower-case hex SHA256; names the cached file and verifies its integrity.
	Sha256        string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetFile) Reset() {
	*x = AssetFile{}
	mi := &file_runtimeworker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetFile) ProtoMessage() {}

func (x *AssetFile) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetFile.ProtoReflect.Descriptor instead.
func (*AssetFile) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{1}
}

func (x *AssetFile) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AssetFile) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// ArchAssets is the set of assets for a single architecture, keyed by asset
// name (a wrapper message because proto map values cannot themselves be maps).
type ArchAssets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         map[string]*AssetFile  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // asset name -> file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchAssets) Reset() {
	*x = ArchAssets{}
	mi := &file_runtimeworker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchAssets) ProtoMessage() {}

func (x *ArchAssets) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchAssets.ProtoReflect.Descriptor instead.
func (*ArchAssets) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{2}
}

func (x *ArchAssets) GetFiles() map[string]*AssetFile {
	if x != nil {
		return x.Files
	}
	return nil
}

// SandboxAssets is the generic, backend-agnostic description of the sandbox
// binaries for an actor: a sandbox class plus assets keyed first by
// architecture (GOARCH) and then by asset name. runtime-worker's backend code
// interprets the asset names (gVisor expects "runsc").
type SandboxAssets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxClass  string                 `protobuf:"bytes,1,opt,name=sandbox_class,json=sandboxClass,proto3" json:"sandbox_class,omitempty"`                                           // e.g. "gvisor"
	Assets        map[string]*ArchAssets `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // arch -> {name -> file}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxAssets) Reset() {
	*x = SandboxAssets{}
	mi := &file_runtimeworker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxAssets) ProtoMessage() {}

func (x *SandboxAssets) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxAssets.ProtoReflect.Descriptor instead.
func (*SandboxAssets) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{3}
}

func (x *SandboxAssets) GetSandboxClass() string {
	if x != nil {
		return x.SandboxClass
	}
	return ""
}

func (x *SandboxAssets) GetAssets() map[string]*ArchAssets {
	if x != nil {
		return x.Assets
	}
	return nil
}

// WorkloadSpec parallels Pod, but with far fewer configurable fields.
type WorkloadSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	PauseImage    string                 `protobuf:"bytes,2,opt,name=pause_image,json=pauseImage,proto3" json:"pause_image,omitempty"`
	Volumes       []*Volume              `protobuf:"bytes,3,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadSpec) Reset() {
	*x = WorkloadSpec{}
	mi := &file_runtimeworker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSpec) ProtoMessage() {}

func (x *WorkloadSpec) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSpec.ProtoReflect.Descriptor instead.
func (*WorkloadSpec) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{4}
}

func (x *WorkloadSpec) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *WorkloadSpec) GetPauseImage() string {
	if x != nil {
		return x.PauseImage
	}
	return ""
}

func (x *WorkloadSpec) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type DurableDirVolume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurableDirVolume) Reset() {
	*x = DurableDirVolume{}
	mi := &file_runtimeworker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurableDirVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurableDirVolume) ProtoMessage() {}

func (x *DurableDirVolume) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurableDirVolume.ProtoReflect.Descriptor instead.
func (*DurableDirVolume) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{5}
}

type Volume struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type  VolumeType             `protobuf:"varint,2,opt,name=type,proto3,enum=actordock.runtimeworker.VolumeType" json:"type,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*Volume_DurableDir
	Source        isVolume_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_runtimeworker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{6}
}

func (x *Volume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Volume) GetType() VolumeType {
	if x != nil {
		return x.Type
	}
	return VolumeType_VOLUME_TYPE_UNSPECIFIED
}

func (x *Volume) GetSource() isVolume_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Volume) GetDurableDir() *DurableDirVolume {
	if x != nil {
		if x, ok := x.Source.(*Volume_DurableDir); ok {
			return x.DurableDir
		}
	}
	return nil
}

type isVolume_Source interface {
	isVolume_Source()
}

type Volume_DurableDir struct {
	DurableDir *DurableDirVolume `protobuf:"bytes,3,opt,name=durable_dir,json=durableDir,proto3,oneof"`
}

func (*Volume_DurableDir) isVolume_Source() {}

type VolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MountPath     string                 `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_runtimeworker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{7}
}

func (x *VolumeMount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeMount) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Command       []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Env           []*EnvEntry            `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	Readyz        *Readyz                `protobuf:"bytes,5,opt,name=readyz,proto3" json:"readyz,omitempty"`
	VolumeMounts  []*VolumeMount         `protobuf:"bytes,6,rep,name=volume_mounts,json=volumeMounts,proto3" json:"volume_mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_runtimeworker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{8}
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Container) GetEnv() []*EnvEntry {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Container) GetReadyz() *Readyz {
	if x != nil {
		return x.Readyz
	}
	return nil
}

func (x *Container) GetVolumeMounts() []*VolumeMount {
	if x != nil {
		return x.VolumeMounts
	}
	return nil
}

type EnvEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvEntry) Reset() {
	*x = EnvEntry{}
	mi := &file_runtimeworker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvEntry) ProtoMessage() {}

func (x *EnvEntry) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvEntry.ProtoReflect.Descriptor instead.
func (*EnvEntry) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{9}
}

func (x *EnvEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Readyz describes how to check that a container is ready to serve.
// Only HTTP is supported today.
type Readyz struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HttpGet       *HTTPGetAction         `protobuf:"bytes,1,opt,name=http_get,json=httpGet,proto3" json:"http_get,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Readyz) Reset() {
	*x = Readyz{}
	mi := &file_runtimeworker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Readyz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Readyz) ProtoMessage() {}

func (x *Readyz) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Readyz.ProtoReflect.Descriptor instead.
func (*Readyz) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{10}
}

func (x *Readyz) GetHttpGet() *HTTPGetAction {
	if x != nil {
		return x.HttpGet
	}
	return nil
}

// HTTPGetAction performs an HTTP GET against the container.
type HTTPGetAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path to access on the HTTP server. Empty means "/readyz".
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// TCP port to connect to (1..65535).
	Port          int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPGetAction) Reset() {
	*x = HTTPGetAction{}
	mi := &file_runtimeworker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPGetAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPGetAction) ProtoMessage() {}

func (x *HTTPGetAction) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPGetAction.ProtoReflect.Descriptor instead.
func (*HTTPGetAction) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{11}
}

func (x *HTTPGetAction) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPGetAction) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_runtimeworker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{12}
}

type LocalCheckpointConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A sub-directory on the local filesystem below which the checkpoint data will be
	// stored.  The structure of the checkpoint should generally be treated as opaque.
	SnapshotPrefix string `protobuf:"bytes,1,opt,name=snapshot_prefix,json=snapshotPrefix,proto3" json:"snapshot_prefix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocalCheckpointConfiguration) Reset() {
	*x = LocalCheckpointConfiguration{}
	mi := &file_runtimeworker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalCheckpointConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalCheckpointConfiguration) ProtoMessage() {}

func (x *LocalCheckpointConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalCheckpointConfiguration.ProtoReflect.Descriptor instead.
func (*LocalCheckpointConfiguration) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{13}
}

func (x *LocalCheckpointConfiguration) GetSnapshotPrefix() string {
	if x != nil {
		return x.SnapshotPrefix
	}
	return ""
}

type ExternalCheckpointConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An object storage URI prefix below which the checkpoint data will be
	// stored.
	//
	// The structure of the checkpoint should generally be treated as opaque. For
	// gVisor, the checkpoint consists of a checkpoint.img file that contains the
	// memory, sentry state, and filesystem deltas.  runtime-sandbox will write additional
	// files to store the WorkloadSpec, which must be reassembled before gVisor
	// can restore a checkpoint.
	//
	// For example: "gs://bucket/actors/1234/snapshots/5678/"
	SnapshotUriPrefix string `protobuf:"bytes,1,opt,name=snapshot_uri_prefix,json=snapshotUriPrefix,proto3" json:"snapshot_uri_prefix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExternalCheckpointConfiguration) Reset() {
	*x = ExternalCheckpointConfiguration{}
	mi := &file_runtimeworker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalCheckpointConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalCheckpointConfiguration) ProtoMessage() {}

func (x *ExternalCheckpointConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalCheckpointConfiguration.ProtoReflect.Descriptor instead.
func (*ExternalCheckpointConfiguration) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{14}
}

func (x *ExternalCheckpointConfiguration) GetSnapshotUriPrefix() string {
	if x != nil {
		return x.SnapshotUriPrefix
	}
	return ""
}

type CheckpointRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TargetSandboxPodUid    string                 `protobuf:"bytes,1,opt,name=target_sandbox_pod_uid,json=targetSandboxPodUid,proto3" json:"target_sandbox_pod_uid,omitempty"`
	ActorTemplateNamespace string                 `protobuf:"bytes,3,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	ActorTemplateName      string                 `protobuf:"bytes,4,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	ActorId                string                 `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Spec                   *WorkloadSpec          `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	Type                   CheckpointType         `protobuf:"varint,9,opt,name=type,proto3,enum=actordock.runtimeworker.CheckpointType" json:"type,omitempty"`
	// The checkpoint configuration, depending on the type.
	//
	// Types that are valid to be assigned to Config:
	//
	//	*CheckpointRequest_LocalConfig
	//	*CheckpointRequest_ExternalConfig
	Config isCheckpointRequest_Config `protobuf_oneof:"config"`
	// What should be included in the checkpoint.
	Scope         SnapshotScope `protobuf:"varint,12,opt,name=scope,proto3,enum=actordock.runtimeworker.SnapshotScope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointRequest) Reset() {
	*x = CheckpointRequest{}
	mi := &file_runtimeworker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRequest) ProtoMessage() {}

func (x *CheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRequest.ProtoReflect.Descriptor instead.
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{15}
}

func (x *CheckpointRequest) GetTargetSandboxPodUid() string {
	if x != nil {
		return x.TargetSandboxPodUid
	}
	return ""
}

func (x *CheckpointRequest) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *CheckpointRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *CheckpointRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *CheckpointRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CheckpointRequest) GetType() CheckpointType {
	if x != nil {
		return x.Type
	}
	return CheckpointType_CHECKPOINT_TYPE_UNSPECIFIED
}

func (x *CheckpointRequest) GetConfig() isCheckpointRequest_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CheckpointRequest) GetLocalConfig() *LocalCheckpointConfiguration {
	if x != nil {
		if x, ok := x.Config.(*CheckpointRequest_LocalConfig); ok {
			return x.LocalConfig
		}
	}
	return nil
}

func (x *CheckpointRequest) GetExternalConfig() *ExternalCheckpointConfiguration {
	if x != nil {
		if x, ok := x.Config.(*CheckpointRequest_ExternalConfig); ok {
			return x.ExternalConfig
		}
	}
	return nil
}

func (x *CheckpointRequest) GetScope() SnapshotScope {
	if x != nil {
		return x.Scope
	}
	return SnapshotScope_SNAPSHOT_SCOPE_UNSPECIFIED
}

type isCheckpointRequest_Config interface {
	isCheckpointRequest_Config()
}

type CheckpointRequest_LocalConfig struct {
	LocalConfig *LocalCheckpointConfiguration `protobuf:"bytes,10,opt,name=local_config,json=localConfig,proto3,oneof"`
}

type CheckpointRequest_ExternalConfig struct {
	ExternalConfig *ExternalCheckpointConfiguration `protobuf:"bytes,11,opt,name=external_config,json=externalConfig,proto3,oneof"`
}

func (*CheckpointRequest_LocalConfig) isCheckpointRequest_Config() {}

func (*CheckpointRequest_ExternalConfig) isCheckpointRequest_Config() {}

type CheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointResponse) Reset() {
	*x = CheckpointResponse{}
	mi := &file_runtimeworker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse) ProtoMessage() {}

func (x *CheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse.ProtoReflect.Descriptor instead.
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{16}
}

type RestoreRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TargetSandboxPodUid    string                 `protobuf:"bytes,1,opt,name=target_sandbox_pod_uid,json=targetSandboxPodUid,proto3" json:"target_sandbox_pod_uid,omitempty"`
	ActorTemplateNamespace string                 `protobuf:"bytes,3,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	ActorTemplateName      string                 `protobuf:"bytes,4,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	ActorId                string                 `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Spec                   *WorkloadSpec          `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	Type                   CheckpointType         `protobuf:"varint,9,opt,name=type,proto3,enum=actordock.runtimeworker.CheckpointType" json:"type,omitempty"`
	// The checkpoint configuration, depending on the type.
	//
	// Types that are valid to be assigned to Config:
	//
	//	*RestoreRequest_LocalConfig
	//	*RestoreRequest_ExternalConfig
	Config isRestoreRequest_Config `protobuf_oneof:"config"`
	// What content to restore from the checkpoint.
	Scope         SnapshotScope `protobuf:"varint,12,opt,name=scope,proto3,enum=actordock.runtimeworker.SnapshotScope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_runtimeworker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{17}
}

func (x *RestoreRequest) GetTargetSandboxPodUid() string {
	if x != nil {
		return x.TargetSandboxPodUid
	}
	return ""
}

func (x *RestoreRequest) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *RestoreRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *RestoreRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *RestoreRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *RestoreRequest) GetType() CheckpointType {
	if x != nil {
		return x.Type
	}
	return CheckpointType_CHECKPOINT_TYPE_UNSPECIFIED
}

func (x *RestoreRequest) GetConfig() isRestoreRequest_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RestoreRequest) GetLocalConfig() *LocalCheckpointConfiguration {
	if x != nil {
		if x, ok := x.Config.(*RestoreRequest_LocalConfig); ok {
			return x.LocalConfig
		}
	}
	return nil
}

func (x *RestoreRequest) GetExternalConfig() *ExternalCheckpointConfiguration {
	if x != nil {
		if x, ok := x.Config.(*RestoreRequest_ExternalConfig); ok {
			return x.ExternalConfig
		}
	}
	return nil
}

func (x *RestoreRequest) GetScope() SnapshotScope {
	if x != nil {
		return x.Scope
	}
	return SnapshotScope_SNAPSHOT_SCOPE_UNSPECIFIED
}

type isRestoreRequest_Config interface {
	isRestoreRequest_Config()
}

type RestoreRequest_LocalConfig struct {
	LocalConfig *LocalCheckpointConfiguration `protobuf:"bytes,10,opt,name=local_config,json=localConfig,proto3,oneof"`
}

type RestoreRequest_ExternalConfig struct {
	ExternalConfig *ExternalCheckpointConfiguration `protobuf:"bytes,11,opt,name=external_config,json=externalConfig,proto3,oneof"`
}

func (*RestoreRequest_LocalConfig) isRestoreRequest_Config() {}

func (*RestoreRequest_ExternalConfig) isRestoreRequest_Config() {}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_runtimeworker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeworker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_runtimeworker_proto_rawDescGZIP(), []int{18}
}

var File_runtimeworker_proto protoreflect.FileDescriptor

const file_runtimeworker_proto_rawDesc = "" +
	"\n" +
	"\x13runtimeworker.proto\x12\x17actordock.runtimeworker\"\xd6\x02\n" +
	"\n" +
	"RunRequest\x123\n" +
	"\x16target_sandbox_pod_uid\x18\x01 \x01(\tR\x13targetSandboxPodUid\x128\n" +
	"\x18actor_template_namespace\x18\x03 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x04 \x01(\tR\x11actorTemplateName\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x129\n" +
	"\x04spec\x18\a \x01(\v2%.actordock.runtimeworker.WorkloadSpecR\x04spec\x12M\n" +
	"\x0esandbox_assets\x18\t \x01(\v2&.actordock.runtimeworker.SandboxAssetsR\rsandboxAssetsJ\x04\b\b\x10\t\"5\n" +
	"\tAssetFile\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"\xb0\x01\n" +
	"\n" +
	"ArchAssets\x12D\n" +
	"\x05files\x18\x01 \x03(\v2..actordock.runtimeworker.ArchAssets.FilesEntryR\x05files\x1a\\\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".actordock.runtimeworker.AssetFileR\x05value:\x028\x01\"\xe0\x01\n" +
	"\rSandboxAssets\x12#\n" +
	"\rsandbox_class\x18\x01 \x01(\tR\fsandboxClass\x12J\n" +
	"\x06assets\x18\x02 \x03(\v22.actordock.runtimeworker.SandboxAssets.AssetsEntryR\x06assets\x1a^\n" +
	"\vAssetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.actordock.runtimeworker.ArchAssetsR\x05value:\x028\x01\"\xae\x01\n" +
	"\fWorkloadSpec\x12B\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\".actordock.runtimeworker.ContainerR\n" +
	"containers\x12\x1f\n" +
	"\vpause_image\x18\x02 \x01(\tR\n" +
	"pauseImage\x129\n" +
	"\avolumes\x18\x03 \x03(\v2\x1f.actordock.runtimeworker.VolumeR\avolumes\"\x12\n" +
	"\x10DurableDirVolume\"\xad\x01\n" +
	"\x06Volume\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\x04type\x18\x02 \x01(\x0e2#.actordock.runtimeworker.VolumeTypeR\x04type\x12L\n" +
	"\vdurable_dir\x18\x03 \x01(\v2).actordock.runtimeworker.DurableDirVolumeH\x00R\n" +
	"durableDirB\b\n" +
	"\x06source\"@\n" +
	"\vVolumeMount\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\"\x88\x02\n" +
	"\tContainer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x123\n" +
	"\x03env\x18\x04 \x03(\v2!.actordock.runtimeworker.EnvEntryR\x03env\x127\n" +
	"\x06readyz\x18\x05 \x01(\v2\x1f.actordock.runtimeworker.ReadyzR\x06readyz\x12I\n" +
	"\rvolume_mounts\x18\x06 \x03(\v2$.actordock.runtimeworker.VolumeMountR\fvolumeMounts\"4\n" +
	"\bEnvEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"K\n" +
	"\x06Readyz\x12A\n" +
	"\bhttp_get\x18\x01 \x01(\v2&.actordock.runtimeworker.HTTPGetActionR\ahttpGet\"7\n" +
	"\rHTTPGetAction\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"\r\n" +
	"\vRunResponse\"G\n" +
	"\x1cLocalCheckpointConfiguration\x12'\n" +
	"\x0fsnapshot_prefix\x18\x01 \x01(\tR\x0esnapshotPrefix\"Q\n" +
	"\x1fExternalCheckpointConfiguration\x12.\n" +
	"\x13snapshot_uri_prefix\x18\x01 \x01(\tR\x11snapshotUriPrefix\"\xda\x04\n" +
	"\x11CheckpointRequest\x123\n" +
	"\x16target_sandbox_pod_uid\x18\x01 \x01(\tR\x13targetSandboxPodUid\x128\n" +
	"\x18actor_template_namespace\x18\x03 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x04 \x01(\tR\x11actorTemplateName\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x129\n" +
	"\x04spec\x18\a \x01(\v2%.actordock.runtimeworker.WorkloadSpecR\x04spec\x12;\n" +
	"\x04type\x18\t \x01(\x0e2'.actordock.runtimeworker.CheckpointTypeR\x04type\x12Z\n" +
	"\flocal_config\x18\n" +
	" \x01(\v25.actordock.runtimeworker.LocalCheckpointConfigurationH\x00R\vlocalConfig\x12c\n" +
	"\x0fexternal_config\x18\v \x01(\v28.actordock.runtimeworker.ExternalCheckpointConfigurationH\x00R\x0eexternalConfig\x12<\n" +
	"\x05scope\x18\f \x01(\x0e2&.actordock.runtimeworker.SnapshotScopeR\x05scopeB\b\n" +
	"\x06configJ\x04\b\x06\x10\aJ\x04\b\b\x10\t\"\x14\n" +
	"\x12CheckpointResponse\"\xd7\x04\n" +
	"\x0eRestoreRequest\x123\n" +
	"\x16target_sandbox_pod_uid\x18\x01 \x01(\tR\x13targetSandboxPodUid\x128\n" +
	"\x18actor_template_namespace\x18\x03 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x04 \x01(\tR\x11actorTemplateName\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x129\n" +
	"\x04spec\x18\a \x01(\v2%.actordock.runtimeworker.WorkloadSpecR\x04spec\x12;\n" +
	"\x04type\x18\t \x01(\x0e2'.actordock.runtimeworker.CheckpointTypeR\x04type\x12Z\n" +
	"\flocal_config\x18\n" +
	" \x01(\v25.actordock.runtimeworker.LocalCheckpointConfigurationH\x00R\vlocalConfig\x12c\n" +
	"\x0fexternal_config\x18\v \x01(\v28.actordock.runtimeworker.ExternalCheckpointConfigurationH\x00R\x0eexternalConfig\x12<\n" +
	"\x05scope\x18\f \x01(\x0e2&.actordock.runtimeworker.SnapshotScopeR\x05scopeB\b\n" +
	"\x06configJ\x04\b\x06\x10\aJ\x04\b\b\x10\t\"\x11\n" +
	"\x0fRestoreResponse*F\n" +
	"\n" +
	"VolumeType\x12\x1b\n" +
	"\x17VOLUME_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17VOLUME_TYPE_DURABLE_DIR\x10\x01*j\n" +
	"\x0eCheckpointType\x12\x1f\n" +
	"\x1bCHECKPOINT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CHECKPOINT_TYPE_LOCAL\x10\x01\x12\x1c\n" +
	"\x18CHECKPOINT_TYPE_EXTERNAL\x10\x02*a\n" +
	"\rSnapshotScope\x12\x1e\n" +
	"\x1aSNAPSHOT_SCOPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SNAPSHOT_SCOPE_FULL\x10\x01\x12\x17\n" +
	"\x13SNAPSHOT_SCOPE_DATA\x10\x022\xab\x02\n" +
	"\fWorkerHerder\x12R\n" +
	"\x03Run\x12#.actordock.runtimeworker.RunRequest\x1a$.actordock.runtimeworker.RunResponse\"\x00\x12g\n" +
	"\n" +
	"Checkpoint\x12*.actordock.runtimeworker.CheckpointRequest\x1a+.actordock.runtimeworker.CheckpointResponse\"\x00\x12^\n" +
	"\aRestore\x12'.actordock.runtimeworker.RestoreRequest\x1a(.actordock.runtimeworker.RestoreResponse\"\x00B=Z;github.com/actordock/runtime/internal/proto/runtimeworkerpbb\x06proto3"

var (
	file_runtimeworker_proto_rawDescOnce sync.Once
	file_runtimeworker_proto_rawDescData []byte
)

func file_runtimeworker_proto_rawDescGZIP() []byte {
	file_runtimeworker_proto_rawDescOnce.Do(func() {
		file_runtimeworker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtimeworker_proto_rawDesc), len(file_runtimeworker_proto_rawDesc)))
	})
	return file_runtimeworker_proto_rawDescData
}

var file_runtimeworker_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_runtimeworker_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_runtimeworker_proto_goTypes = []any{
	(VolumeType)(0),                         // 0: actordock.runtimeworker.VolumeType
	(CheckpointType)(0),                     // 1: actordock.runtimeworker.CheckpointType
	(SnapshotScope)(0),                      // 2: actordock.runtimeworker.SnapshotScope
	(*RunRequest)(nil),                      // 3: actordock.runtimeworker.RunRequest
	(*AssetFile)(nil),                       // 4: actordock.runtimeworker.AssetFile
	(*ArchAssets)(nil),                      // 5: actordock.runtimeworker.ArchAssets
	(*SandboxAssets)(nil),                   // 6: actordock.runtimeworker.SandboxAssets
	(*WorkloadSpec)(nil),                    // 7: actordock.runtimeworker.WorkloadSpec
	(*DurableDirVolume)(nil),                // 8: actordock.runtimeworker.DurableDirVolume
	(*Volume)(nil),                          // 9: actordock.runtimeworker.Volume
	(*VolumeMount)(nil),                     // 10: actordock.runtimeworker.VolumeMount
	(*Container)(nil),                       // 11: actordock.runtimeworker.Container
	(*EnvEntry)(nil),                        // 12: actordock.runtimeworker.EnvEntry
	(*Readyz)(nil),                          // 13: actordock.runtimeworker.Readyz
	(*HTTPGetAction)(nil),                   // 14: actordock.runtimeworker.HTTPGetAction
	(*RunResponse)(nil),                     // 15: actordock.runtimeworker.RunResponse
	(*LocalCheckpointConfiguration)(nil),    // 16: actordock.runtimeworker.LocalCheckpointConfiguration
	(*ExternalCheckpointConfiguration)(nil), // 17: actordock.runtimeworker.ExternalCheckpointConfiguration
	(*CheckpointRequest)(nil),               // 18: actordock.runtimeworker.CheckpointRequest
	(*CheckpointResponse)(nil),              // 19: actordock.runtimeworker.CheckpointResponse
	(*RestoreRequest)(nil),                  // 20: actordock.runtimeworker.RestoreRequest
	(*RestoreResponse)(nil),                 // 21: actordock.runtimeworker.RestoreResponse
	nil,                                     // 22: actordock.runtimeworker.ArchAssets.FilesEntry
	nil,                                     // 23: actordock.runtimeworker.SandboxAssets.AssetsEntry
}
var file_runtimeworker_proto_depIdxs = []int32{
	7,  // 0: actordock.runtimeworker.RunRequest.spec:type_name -> actordock.runtimeworker.WorkloadSpec
	6,  // 1: actordock.runtimeworker.RunRequest.sandbox_assets:type_name -> actordock.runtimeworker.SandboxAssets
	22, // 2: actordock.runtimeworker.ArchAssets.files:type_name -> actordock.runtimeworker.ArchAssets.FilesEntry
	23, // 3: actordock.runtimeworker.SandboxAssets.assets:type_name -> actordock.runtimeworker.SandboxAssets.AssetsEntry
	11, // 4: actordock.runtimeworker.WorkloadSpec.containers:type_name -> actordock.runtimeworker.Container
	9,  // 5: actordock.runtimeworker.WorkloadSpec.volumes:type_name -> actordock.runtimeworker.Volume
	0,  // 6: actordock.runtimeworker.Volume.type:type_name -> actordock.runtimeworker.VolumeType
	8,  // 7: actordock.runtimeworker.Volume.durable_dir:type_name -> actordock.runtimeworker.DurableDirVolume
	12, // 8: actordock.runtimeworker.Container.env:type_name -> actordock.runtimeworker.EnvEntry
	13, // 9: actordock.runtimeworker.Container.readyz:type_name -> actordock.runtimeworker.Readyz
	10, // 10: actordock.runtimeworker.Container.volume_mounts:type_name -> actordock.runtimeworker.VolumeMount
	14, // 11: actordock.runtimeworker.Readyz.http_get:type_name -> actordock.runtimeworker.HTTPGetAction
	7,  // 12: actordock.runtimeworker.CheckpointRequest.spec:type_name -> actordock.runtimeworker.WorkloadSpec
	1,  // 13: actordock.runtimeworker.CheckpointRequest.type:type_name -> actordock.runtimeworker.CheckpointType
	16, // 14: actordock.runtimeworker.CheckpointRequest.local_config:type_name -> actordock.runtimeworker.LocalCheckpointConfiguration
	17, // 15: actordock.runtimeworker.CheckpointRequest.external_config:type_name -> actordock.runtimeworker.ExternalCheckpointConfiguration
	2,  // 16: actordock.runtimeworker.CheckpointRequest.scope:type_name -> actordock.runtimeworker.SnapshotScope
	7,  // 17: actordock.runtimeworker.RestoreRequest.spec:type_name -> actordock.runtimeworker.WorkloadSpec
	1,  // 18: actordock.runtimeworker.RestoreRequest.type:type_name -> actordock.runtimeworker.CheckpointType
	16, // 19: actordock.runtimeworker.RestoreRequest.local_config:type_name -> actordock.runtimeworker.LocalCheckpointConfiguration
	17, // 20: actordock.runtimeworker.RestoreRequest.external_config:type_name -> actordock.runtimeworker.ExternalCheckpointConfiguration
	2,  // 21: actordock.runtimeworker.RestoreRequest.scope:type_name -> actordock.runtimeworker.SnapshotScope
	4,  // 22: actordock.runtimeworker.ArchAssets.FilesEntry.value:type_name -> actordock.runtimeworker.AssetFile
	5,  // 23: actordock.runtimeworker.SandboxAssets.AssetsEntry.value:type_name -> actordock.runtimeworker.ArchAssets
	3,  // 24: actordock.runtimeworker.WorkerHerder.Run:input_type -> actordock.runtimeworker.RunRequest
	18, // 25: actordock.runtimeworker.WorkerHerder.Checkpoint:input_type -> actordock.runtimeworker.CheckpointRequest
	20, // 26: actordock.runtimeworker.WorkerHerder.Restore:input_type -> actordock.runtimeworker.RestoreRequest
	15, // 27: actordock.runtimeworker.WorkerHerder.Run:output_type -> actordock.runtimeworker.RunResponse
	19, // 28: actordock.runtimeworker.WorkerHerder.Checkpoint:output_type -> actordock.runtimeworker.CheckpointResponse
	21, // 29: actordock.runtimeworker.WorkerHerder.Restore:output_type -> actordock.runtimeworker.RestoreResponse
	27, // [27:30] is the sub-list for method output_type
	24, // [24:27] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_runtimeworker_proto_init() }
func file_runtimeworker_proto_init() {
	if File_runtimeworker_proto != nil {
		return
	}
	file_runtimeworker_proto_msgTypes[6].OneofWrappers = []any{
		(*Volume_DurableDir)(nil),
	}
	file_runtimeworker_proto_msgTypes[15].OneofWrappers = []any{
		(*CheckpointRequest_LocalConfig)(nil),
		(*CheckpointRequest_ExternalConfig)(nil),
	}
	file_runtimeworker_proto_msgTypes[17].OneofWrappers = []any{
		(*RestoreRequest_LocalConfig)(nil),
		(*RestoreRequest_ExternalConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtimeworker_proto_rawDesc), len(file_runtimeworker_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtimeworker_proto_goTypes,
		DependencyIndexes: file_runtimeworker_proto_depIdxs,
		EnumInfos:         file_runtimeworker_proto_enumTypes,
		MessageInfos:      file_runtimeworker_proto_msgTypes,
	}.Build()
	File_runtimeworker_proto = out.File
	file_runtimeworker_proto_goTypes = nil
	file_runtimeworker_proto_depIdxs = nil
}
