{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "actordock-stack.namespace" . }}
  labels:
    {{- include "actordock-stack.labels" . | nindent 4 }}
{{- end }}
