# Copyright 2026 The Actordock Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# shellcheck shell=bash

actordock_root() {
  cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd
}

log_step() {
  printf '\033[1;36m[step] %s\033[0m\n' "$1" >&2
}

die() {
  echo "error: $*" >&2
  exit 1
}

require_cmd() {
  local cmd
  for cmd in "$@"; do
    command -v "${cmd}" >/dev/null 2>&1 || die "missing required command: ${cmd}"
  done
}

load_substrate_lock() {
  local lock_file="$1"
  [[ -f "${lock_file}" ]] || die "missing ${lock_file}"

  SUBSTRATE_REPO=""
  SUBSTRATE_COMMIT=""
  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%%#*}"
    line="${line#"${line%%[![:space:]]*}"}"
    [[ -z "${line}" ]] && continue
    case "${line}" in
      repository=*) SUBSTRATE_REPO="${line#repository=}" ;;
      commit=*) SUBSTRATE_COMMIT="${line#commit=}" ;;
    esac
  done <"${lock_file}"

  [[ -n "${SUBSTRATE_REPO}" && -n "${SUBSTRATE_COMMIT}" ]] \
    || die "invalid ${lock_file}: need repository= and commit="
}

ensure_substrate_root() {
  local root="$1"
  if [[ -n "${SUBSTRATE_ROOT:-}" ]]; then
    [[ -f "${SUBSTRATE_ROOT}/hack/install-ate-kind.sh" ]] \
      || die "SUBSTRATE_ROOT does not look like Agent Substrate: ${SUBSTRATE_ROOT}"
    printf '%s\n' "${SUBSTRATE_ROOT}"
    return
  fi

  load_substrate_lock "${root}/substrate.lock"
  local checkout_dir="${root}/.substrate"
  if [[ ! -d "${checkout_dir}/.git" ]]; then
    log_step "Cloning Substrate (${SUBSTRATE_COMMIT})"
    git -c advice.detachedHead=false clone "${SUBSTRATE_REPO}" "${checkout_dir}"
  fi

  log_step "Checking out Substrate ${SUBSTRATE_COMMIT}"
  git -C "${checkout_dir}" fetch origin --tags
  git -C "${checkout_dir}" checkout --force "${SUBSTRATE_COMMIT}"
  printf '%s\n' "${checkout_dir}"
}

ensure_ko() {
  if command -v ko >/dev/null 2>&1; then
    return
  fi
  log_step "Installing ko"
  go install github.com/google/ko@latest
  export PATH="${PATH}:$(go env GOPATH)/bin"
  command -v ko >/dev/null 2>&1 || die "ko not found after install"
}

kubectl_ctx() {
  kubectl --context "kind-${KIND_CLUSTER_NAME}" "$@"
}

wait_substrate_control_plane() {
  log_step "Waiting for Substrate control plane"
  kubectl_ctx rollout status statefulset/valkey-cluster -n ate-system --timeout=300s
  kubectl_ctx rollout status deployment/ate-api-server-deployment -n ate-system --timeout=300s
  kubectl_ctx rollout status deployment/ate-controller -n ate-system --timeout=300s
  kubectl_ctx rollout status deployment/atenet-router -n ate-system --timeout=300s
  kubectl_ctx rollout status daemonset/atelet -n ate-system --timeout=300s
}

deploy_actordock_images() {
  local root="$1"
  local substrate_root="$2"

  ensure_ko
  export KO_DEFAULTPLATFORMS="linux/$(go env GOARCH)"

  log_step "Ensuring actordock namespace"
  kubectl_ctx apply -f "${root}/manifests/local/namespace.yaml"

  log_step "Deploying WorkerPool"
  (cd "${substrate_root}" && ko resolve -f "${root}/manifests/substrate/workerpool.yaml") \
    | kubectl_ctx apply -f -

  log_step "Deploying ActorTemplate base"
  kubectl_ctx delete actortemplate base -n actordock --ignore-not-found
  if kubectl_ctx get actortemplate base -n actordock >/dev/null 2>&1; then
    kubectl_ctx wait --for=delete actortemplate/base -n actordock --timeout=120s
  fi
  sed "s|\${BUCKET_NAME}|${BUCKET_NAME:-ate-snapshots}|g" \
    "${root}/manifests/substrate/actortemplate-base.yaml.tmpl" \
    | (cd "${root}" && ko resolve -f -) \
    | kubectl_ctx apply -f -

  log_step "Deploying Actordock platform and router"
  kubectl kustomize "${root}/manifests/local" --load-restrictor LoadRestrictionsNone \
    | (cd "${root}" && ko resolve -f -) \
    | kubectl_ctx apply -f -

  log_step "Waiting for Actordock workloads"
  kubectl_ctx rollout status deployment/platform -n actordock --timeout=180s
  kubectl_ctx rollout status deployment/router -n actordock --timeout=180s

  wait_actortemplate_base
}

wait_actortemplate_base() {
  log_step "Waiting for ActorTemplate base golden snapshot"
  kubectl_ctx wait --for=condition=Ready actortemplate/base -n actordock --timeout=600s
}

write_env_local() {
  local root="$1"
  cat >"${root}/hack/.env.local" <<EOF
# Generated by hack/install-local.sh — source before running ./hack/verify-local.sh
export E2B_API_URL=http://localhost:8080
export E2B_SANDBOX_URL=http://localhost:8081
export E2B_DOMAIN=localhost
export E2B_API_KEY=dev
export E2B_VALIDATE_API_KEY=false
export KUBECONFIG=\${KUBECONFIG:-~/.kube/config}
EOF
}
