# Copyright 2026 The Actordock Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# shellcheck shell=bash

actordock_root() {
  cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd
}

log_step() {
  printf '\033[1;36m[step] %s\033[0m\n' "$1" >&2
}

die() {
  echo "error: $*" >&2
  exit 1
}

require_cmd() {
  local cmd
  for cmd in "$@"; do
    command -v "${cmd}" >/dev/null 2>&1 || die "missing required command: ${cmd}"
  done
}

ensure_runtime_root() {
  local root="$1"
  if [[ -n "${RUNTIME_ROOT:-}" ]]; then
    [[ -f "${RUNTIME_ROOT}/hack/install-runtime-kind.sh" ]] \
      || die "RUNTIME_ROOT does not look like actordock runtime: ${RUNTIME_ROOT}"
    printf '%s\n' "${RUNTIME_ROOT}"
    return
  fi

  local runtime_dir="${root}/runtime"
  [[ -f "${runtime_dir}/hack/install-runtime-kind.sh" ]] \
    || die "missing vendored runtime at ${runtime_dir}"
  printf '%s\n' "${runtime_dir}"
}

ensure_ko() {
  if command -v ko >/dev/null 2>&1; then
    return
  fi
  log_step "Installing ko"
  go install github.com/google/ko@latest
  export PATH="${PATH}:$(go env GOPATH)/bin"
  command -v ko >/dev/null 2>&1 || die "ko not found after install"
}

kubectl_ctx() {
  kubectl --context "kind-${KIND_CLUSTER_NAME}" "$@"
}

wait_valkey_cluster_ready() {
  local timeout="${1:-600s}"
  log_step "Waiting for Valkey cluster (${timeout})"
  kubectl_ctx rollout status statefulset/valkey-cluster -n actordock-system --timeout="${timeout}"
  kubectl_ctx wait --for=condition=complete job/valkey-cluster-init -n actordock-system --timeout="${timeout}"
}

wait_runtime_control_plane() {
  local timeout="${1:-600s}"
  log_step "Waiting for runtime control plane (${timeout})"
  wait_valkey_cluster_ready "${timeout}"
  kubectl_ctx rollout status deployment/runtime-controller -n actordock-system --timeout="${timeout}"
  kubectl_ctx rollout status deployment/runtime-net-router -n actordock-system --timeout="${timeout}"
  kubectl_ctx rollout status daemonset/runtime-worker -n actordock-system --timeout="${timeout}"
  kubectl_ctx rollout status deployment/runtime-api -n actordock-system --timeout="${timeout}"
}

deploy_actordock_images() {
  local root="$1"
  local runtime_root="$2"

  ensure_ko
  export KO_DEFAULTPLATFORMS="linux/$(go env GOARCH)"

  log_step "Ensuring actordock namespace"
  kubectl_ctx apply -f "${root}/manifests/local/namespace.yaml"

  log_step "Deploying WorkerPool"
  (cd "${runtime_root}" && ko resolve -f "${root}/manifests/runtime/workerpool.yaml") \
    | kubectl_ctx apply -f -

  apply_actortemplate "${root}" base "${root}/manifests/runtime/actortemplate-base.yaml.tmpl"

  log_step "Building dashboard web assets"
  require_cmd npm
  (cd "${root}/dashboard/web" && npm ci && npm run build)

  log_step "Deploying Actordock platform, router, scheduler, and dashboard"
  kubectl kustomize "${root}/manifests/local" --load-restrictor LoadRestrictionsNone \
    | (cd "${root}" && ko resolve -f -) \
    | kubectl_ctx apply -f -

  log_step "Waiting for Actordock workloads"
  kubectl_ctx rollout status deployment/redis -n actordock --timeout=120s
  kubectl_ctx rollout status deployment/platform -n actordock --timeout=180s
  kubectl_ctx rollout status deployment/router -n actordock --timeout=180s
  kubectl_ctx rollout status deployment/scheduler -n actordock --timeout=180s
  kubectl_ctx rollout status deployment/template-builder -n actordock --timeout=180s
  kubectl_ctx rollout status deployment/dashboard -n actordock --timeout=180s

  wait_actortemplate_ready base
}

apply_actortemplate() {
  local root="$1"
  local name="$2"
  local manifest="$3"

  log_step "Deploying ActorTemplate ${name}"
  kubectl_ctx delete actortemplate "${name}" -n actordock --ignore-not-found
  if kubectl_ctx get actortemplate "${name}" -n actordock >/dev/null 2>&1; then
    kubectl_ctx wait --for=delete actortemplate/"${name}" -n actordock --timeout=120s
  fi
  sed "s|\${BUCKET_NAME}|${BUCKET_NAME:-actordock-snapshots}|g" \
    "${manifest}" \
    | (cd "${root}" && ko resolve -f -) \
    | kubectl_ctx apply -f -
}

wait_actortemplate_ready() {
  log_step "Waiting for ActorTemplate ${1} golden snapshot"
  kubectl_ctx wait --for=condition=Ready actortemplate/"${1}" -n actordock --timeout=600s
}

write_env_local() {
  local root="$1"
  cat >"${root}/hack/.env.local" <<EOF
# Generated by hack/install-local.sh — source before running ./hack/verify-local.sh
export E2B_API_URL=http://localhost:8080
export E2B_SANDBOX_URL=http://localhost:8081
export E2B_DOMAIN=localhost
export E2B_API_KEY=dev
export E2B_VALIDATE_API_KEY=false
export DASHBOARD_URL=http://localhost:3000
export KUBECONFIG=\${KUBECONFIG:-~/.kube/config}
EOF
}
